# Generated by Django 5.0.4 on 2024-05-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, blank=False)),
                ("description", models.TextField(default="")),
                ("content", models.TextField(default="")),
            ],
            options={
                "db_table": "articles",
            },
        ),
    ]
